name: ServerManagement
version: '${project.version}'
main: org.diegooo.servermanagement.ServerManagement
commands:
  setmaxplayers:
  servermanagement:
  setmotd:
  seticon:
    aliases:
      - serversettingsgui
      - serversettings
  setworldspawn:
    aliases:
      - setspawn
  spawn: