name: ServerManagement
version: '${project.version}'
main: org.diegooo.servermanagement.ServerManagement
commands:
  setmaxplayers:
    description: Sets max players allowed on the server
  servermanagement:
    description: Plugin overview.
  setmotd:
    description: Sets the server MOTD.
  seticon:
    description: Sets the server icon.
  setworldspawn:
    aliases:
      - setspawn
    description: Sets the spawn of the specified world.
  spawn:
    description: Teleport you to the spawn point of the specified world.
  settings:
    aliases:
      - serversettings
      - servermanagementmenu
    description: Opens the server settings menu.